app:
    resource: '@AppBundle/Controller/'
    type: annotation

avanzu_admin:
    prefix: /admin
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"